"""Seed: справочник услуг, типы документов, вопросы интервью и три синтетических кейса.

Все данные вымышленные. Какие шаги попадут в план, решает rules.py; здесь только справочные данные.
Поля egov_url не заполняем, пока их не проверят по официальным источникам.
"""

AGENCIES = {"MED": "медицина", "EDU": "образование", "SOC": "соцзащита"}
DOMAINS = ("health", "communication", "education", "daily_skills", "accessibility", "family_support")
DOMAIN_LABELS = {
    "health": "Здоровье",
    "communication": "Общение и речь",
    "education": "Обучение",
    "daily_skills": "Бытовые навыки",
    "accessibility": "Доступность среды",
    "family_support": "Поддержка семьи",
}
CHANNELS = {
    "egov": "eGov (онлайн)",
    "polyclinic": "Поликлиника",
    "pmpk": "ПМПК",
    "social_dept": "Отдел соцзащиты",
    "school": "Школа / отдел образования",
}
STAGES = {
    "early": "Раннее вмешательство",
    "correction": "Коррекция",
    "socialization": "Социализация",
}

# --- Единая папка документов ---
DOC_TYPES: list[dict] = [
    {"id": "ID_PARENT", "name": "Удостоверение личности родителя", "note": ""},
    {"id": "BIRTH_CERT", "name": "Свидетельство о рождении ребёнка", "note": ""},
    {"id": "MED_CONCLUSION", "name": "Выписка или заключение врача", "note": ""},
    {"id": "MED_CARD_052", "name": "Медицинская карта (форма 052/у)", "note": ""},
    {"id": "PMPK_CONCLUSION", "name": "Заключение ПМПК", "note": ""},
    {"id": "MSE_CERT", "name": "Справка об инвалидности (МСЭ)", "note": "Действует до даты, указанной в справке"},
    {"id": "IPR_EXTRACT", "name": "Выписка из ИПР", "note": ""},
    {"id": "IPR_UPDATED", "name": "Обновлённая ИПР (для продления)", "note": ""},
    {"id": "PSYCH_FRESH", "name": "Актуальное заключение психиатра", "note": "Обычно не старше 1–3 месяцев"},
    {"id": "NEURO_CONSULT", "name": "Консультация невролога", "note": ""},
    {"id": "DYNAMICS_REPORT", "name": "Заключение психолога или логопеда о динамике развития", "note": ""},
    {"id": "VKK_031", "name": "Заключение ВКК (форма 031/у)", "note": "Действует не более месяца — получайте ближе к подаче заявления"},
    {"id": "INSTITUTION_REPORT", "name": "Характеристика из детского сада или школы", "note": ""},
    {"id": "CHILD_WORKS", "name": "Работы ребёнка (рисунки, тетради) для ПМПК", "note": ""},
    {"id": "APPLICATION_COPIES", "name": "Копии заявлений и ответов ведомств", "note": ""},
]
DOC_TYPES_BY_ID = {d["id"]: d for d in DOC_TYPES}

# --- Справочник услуг ---
# executor: agency — шаг выполняет ведомство; family — заявление подаёт семья (owner = член семьи).
# produces: какие документы появляются у семьи, когда шаг выполнен.
SERVICES: list[dict] = [
    {
        "id": "MED_PEDIATRICIAN",
        "title": "Консультация участкового педиатра",
        "domain": "health",
        "channel": "polyclinic",
        "description": "Педиатр по месту прикрепления выдаёт направления к профильным специалистам и на реабилитацию. "
                       "На приёме можно спросить о направлении к специалистам и в центр раннего вмешательства.",
        "how_to": "Запишитесь в поликлинику по месту прикрепления через регистратуру или онлайн. Расскажите, что вас беспокоит, "
                  "и спросите о направлениях к специалистам и в центр раннего вмешательства.",
        "typical_duration": "Приём в течение 1–2 недель после записи",
        "required_documents": ["ID_PARENT", "BIRTH_CERT"],
        "default_deadline_days": 7,
        "responsible": "Участковый педиатр поликлиники",
        "executor": "agency",
        "default_explanation": "Педиатр — первая точка входа в маршрут: он выдаёт направления к специалистам. "
                               "Помощь в раннем возрасте можно начинать, не дожидаясь окончания обследования.",
    },
    {
        "id": "MED_MCHAT",
        "title": "Скрининг развития M-CHAT-R",
        "domain": "health",
        "channel": "polyclinic",
        "description": "Короткий опросник для родителей детей 16–30 месяцев, который проводят в поликлинике.",
        "how_to": "Попросите педиатра провести скрининг M-CHAT-R — это опросник для родителей, он занимает несколько минут.",
        "typical_duration": "В день приёма",
        "required_documents": ["BIRTH_CERT"],
        "default_deadline_days": 14,
        "responsible": "Участковый педиатр поликлиники",
        "executor": "agency",
        "default_explanation": "Короткий опросник помогает понять, нужны ли консультации специалистов. "
                               "Его проходят в возрасте от 16 до 30 месяцев.",
    },
    {
        "id": "MED_CONCLUSION_COPY",
        "title": "Получить выписку или заключение врача",
        "domain": "health",
        "channel": "polyclinic",
        "description": "Если заключение врача есть, но на руках его нет, выписку выдаёт поликлиника.",
        "how_to": "Обратитесь в поликлинику, где наблюдается ребёнок, и попросите выписку из медицинской карты.",
        "typical_duration": "1–5 рабочих дней",
        "required_documents": ["ID_PARENT"],
        "default_deadline_days": 7,
        "responsible": "Поликлиника по месту прикрепления",
        "executor": "agency",
        "produces": ["MED_CONCLUSION"],
        "default_explanation": "Выписка врача понадобится почти во всех ведомствах, поэтому её стоит получить первой.",
    },
    {
        "id": "MED_FOLLOWUP",
        "title": "Плановый визит к врачу",
        "domain": "health",
        "channel": "polyclinic",
        "description": "Регулярное наблюдение у врача и выполнение его назначений.",
        "how_to": "Запишитесь на следующий визит к врачу, который наблюдает ребёнка, и возьмите с собой медицинскую карту.",
        "typical_duration": "Запись на 1–3 недели вперёд",
        "required_documents": ["MED_CARD_052"],
        "default_deadline_days": 30,
        "responsible": "Врач, наблюдающий ребёнка",
        "executor": "agency",
        "default_explanation": "Регулярные визиты к врачу нужны, чтобы документы для других ведомств оставались актуальными.",
    },
    {
        "id": "MED_MSE_REF",
        "title": "Направление на МСЭ (поликлиника и ВКК)",
        "domain": "health",
        "channel": "polyclinic",
        "description": "Поликлиника готовит документы и заключение врачебно-консультативной комиссии (форма 031/у) для МСЭ.",
        "how_to": "Попросите врача оформить направление на МСЭ через врачебно-консультативную комиссию (ВКК, форма 031/у).",
        "typical_duration": "До 2–4 недель",
        "required_documents": ["MED_CONCLUSION", "MED_CARD_052", "INSTITUTION_REPORT"],
        "default_deadline_days": 30,
        "responsible": "Врачебно-консультативная комиссия поликлиники",
        "executor": "agency",
        "produces": ["VKK_031"],
        "default_explanation": "Без направления из поликлиники нельзя пройти освидетельствование и получить доступ к мерам поддержки.",
    },
    {
        "id": "MED_REHAB",
        "title": "Медицинская реабилитация в центрах «Қамқорлық»",
        "domain": "health",
        "channel": "polyclinic",
        "description": "Занятия в реабилитационном центре по направлению поликлиники, бесплатно по программе. Метод подбирает специалист центра.",
        "how_to": "Попросите в поликлинике направление в реабилитационный центр.",
        "typical_duration": "По очереди центра",
        "required_documents": ["MED_CONCLUSION", "MED_CARD_052"],
        "default_deadline_days": 30,
        "responsible": "Поликлиника и реабилитационный центр",
        "executor": "agency",
        "default_explanation": "Центр даёт регулярные занятия со специалистами; какие именно — решает специалист центра.",
    },
    {
        "id": "EDU_PMPK",
        "title": "Обследование на ПМПК",
        "domain": "education",
        "channel": "egov",
        "description": "Психолого-медико-педагогическая консультация даёт рекомендации по условиям обучения: детский сад, школа, "
                       "тьютор, адаптированная программа. Школу комиссия не выбирает.",
        "how_to": "Заявление подаёт родитель на eGov. Точный перечень документов — в описании услуги на egov.kz.",
        "typical_duration": "Запись по очереди ПМПК",
        "required_documents": ["MED_CARD_052", "MED_CONCLUSION", "CHILD_WORKS"],
        "optional_documents": ["MSE_CERT"],
        "default_deadline_days": 30,
        "responsible": "Психолого-медико-педагогическая консультация (ПМПК)",
        "executor": "family",
        "produces": ["PMPK_CONCLUSION"],
        "default_explanation": "Заключение ПМПК открывает образовательный маршрут: без него школа не может назначить тьютора "
                               "и адаптированную программу.",
    },
    {
        "id": "EDU_TUTOR",
        "title": "Тьютор в школе",
        "domain": "education",
        "channel": "school",
        "description": "Школа назначает тьютора по рекомендации ПМПК.",
        "how_to": "Подайте заявление на имя директора школы и приложите заключение ПМПК.",
        "typical_duration": "До 1 месяца",
        "required_documents": ["PMPK_CONCLUSION"],
        "default_deadline_days": 30,
        "responsible": "Администрация школы и отдел образования",
        "executor": "agency",
        "default_explanation": "Тьютор помогает ребёнку учиться в классе вместе со сверстниками.",
    },
    {
        "id": "EDU_ADAPTED_PROGRAM",
        "title": "Адаптированная программа и помощь специалистов в школе",
        "domain": "education",
        "channel": "school",
        "description": "По заключению ПМПК школа создаёт условия: адаптированная программа, помощь психолога, логопеда, дефектолога.",
        "how_to": "Передайте заключение ПМПК в школу и попросите составить адаптированную программу.",
        "typical_duration": "До 1 месяца",
        "required_documents": ["PMPK_CONCLUSION"],
        "default_deadline_days": 30,
        "responsible": "Администрация школы",
        "executor": "agency",
        "default_explanation": "Адаптированная программа и помощь специалистов позволяют ребёнку учиться в своём темпе.",
    },
    {
        "id": "EDU_SPEC_CLASS",
        "title": "Специальный класс или специальная организация образования",
        "domain": "education",
        "channel": "school",
        "description": "Место в специальном классе или организации по рекомендации ПМПК.",
        "how_to": "Обратитесь в отдел образования с заключением ПМПК.",
        "typical_duration": "До 1 месяца",
        "required_documents": ["PMPK_CONCLUSION", "BIRTH_CERT"],
        "default_deadline_days": 30,
        "responsible": "Отдел образования",
        "executor": "agency",
        "default_explanation": "Специальный класс даёт ребёнку условия обучения, которые рекомендовала комиссия.",
    },
    {
        "id": "EDU_REHAB",
        "title": "Коррекционные занятия по рекомендации ПМПК",
        "domain": "communication",
        "channel": "pmpk",
        "description": "Бесплатные занятия с логопедом, дефектологом, психологом (КППК, реабилитационные центры образования).",
        "how_to": "С заключением ПМПК обратитесь в кабинет психолого-педагогической коррекции по месту жительства.",
        "typical_duration": "По очереди кабинета",
        "required_documents": ["PMPK_CONCLUSION"],
        "default_deadline_days": 21,
        "responsible": "Кабинет психолого-педагогической коррекции",
        "executor": "agency",
        "default_explanation": "Регулярные занятия со специалистами — то, что рекомендовала комиссия; их нужно начать как можно раньше.",
    },
    {
        "id": "SOC_MSE",
        "title": "Первичное освидетельствование МСЭ",
        "domain": "family_support",
        "channel": "social_dept",
        "description": "Медико-социальная экспертиза: путь — поликлиника, затем ВКК, затем МСЭ. "
                       "Инвалидность устанавливают не по диагнозу, а по степени ограничений жизнедеятельности.",
        "how_to": "После направления из поликлиники подайте заявление на освидетельствование.",
        "typical_duration": "До 10 рабочих дней",
        "required_documents": ["VKK_031", "MED_CONCLUSION", "MED_CARD_052", "INSTITUTION_REPORT", "BIRTH_CERT", "ID_PARENT"],
        "default_deadline_days": 30,
        "responsible": "Отдел медико-социальной экспертизы",
        "executor": "family",
        "produces": ["MSE_CERT", "IPR_EXTRACT"],
        "default_explanation": "Справка МСЭ открывает доступ к пособиям, социальным услугам и средствам по ИПР.",
    },
    {
        "id": "SOC_MSE_REEXAM",
        "title": "Переосвидетельствование МСЭ (продление справки)",
        "domain": "family_support",
        "channel": "egov",
        "description": "Продление инвалидности до окончания срока справки. Результат — новая справка и выписка из ИПР в кабинете eGov.",
        # TODO(verify): service name taken from egov.kz / inva.gov.kz search results; confirm the exact wording on egov.kz.
        "how_to": "Подайте заявление на eGov: услуга «Установление инвалидности и/или степени утраты трудоспособности и/или "
                  "определение необходимых мер социальной защиты», подпись ЭЦП или SMS-кодом. "
                  "Заключение ВКК действует не более месяца — получайте его ближе к подаче.",
        "typical_duration": "Очно — в тот же день; заочно — до 3 рабочих дней; с консультацией или очным освидетельствованием — до 10 рабочих дней",
        "required_documents": ["VKK_031", "PSYCH_FRESH", "NEURO_CONSULT", "DYNAMICS_REPORT", "IPR_UPDATED", "INSTITUTION_REPORT"],
        "optional_documents": ["PMPK_CONCLUSION"],
        "extra_notes": ["Анализы — по запросу комиссии"],
        "default_deadline_days": 30,
        "due_soon_days": 30,
        "responsible": "Отдел медико-социальной экспертизы",
        "executor": "family",
        "produces": ["MSE_CERT", "IPR_EXTRACT"],
        "default_explanation": "Если не продлить справку вовремя, выплаты и услуги по ИПР приостанавливаются. "
                               "Документы лучше собирать заранее.",
    },
    {
        "id": "SOC_BENEFIT",
        "title": "Пособия по инвалидности и по уходу",
        "domain": "family_support",
        "channel": "social_dept",
        "description": "Государственные пособия при действующей справке МСЭ. Виды и порядок уточняются в отделе соцзащиты.",
        "how_to": "Обратитесь в отдел занятости и социальных программ или на eGov с действующей справкой МСЭ.",
        "typical_duration": "Уточняется в отделе соцзащиты",
        "required_documents": ["MSE_CERT", "ID_PARENT", "BIRTH_CERT"],
        "default_deadline_days": 30,
        "responsible": "Отдел занятости и социальных программ",
        "executor": "family",
        "default_explanation": "Пособие положено при действующей справке — оформите его, чтобы не терять выплаты.",
    },
    {
        "id": "SOC_TSR",
        "title": "Технические средства по ИПР",
        "domain": "accessibility",
        "channel": "social_dept",
        "description": "Технические средства, положенные ребёнку по индивидуальной программе.",
        "how_to": "Обратитесь в отдел соцзащиты с выпиской из ИПР.",
        "typical_duration": "Уточняется в отделе соцзащиты",
        "required_documents": ["IPR_EXTRACT", "MSE_CERT"],
        "default_deadline_days": 30,
        "responsible": "Отдел занятости и социальных программ",
        "executor": "family",
        "default_explanation": "Средства из ИПР положены ребёнку бесплатно — их стоит получить.",
    },
    {
        "id": "SOC_SANATORIUM",
        "title": "Санаторно-курортное направление по ИПР",
        "domain": "health",
        "channel": "social_dept",
        "description": "Направление в санаторий, если оно предусмотрено индивидуальной программой.",
        "how_to": "Обратитесь в отдел соцзащиты с выпиской из ИПР.",
        "typical_duration": "По очереди",
        "required_documents": ["IPR_EXTRACT", "MSE_CERT", "MED_CARD_052"],
        "default_deadline_days": 30,
        "responsible": "Отдел занятости и социальных программ",
        "executor": "family",
        "default_explanation": "Если направление предусмотрено ИПР, его можно получить по очереди.",
    },
    {
        "id": "SOC_SOCIAL_SERVICES",
        "title": "Специальные социальные услуги",
        "domain": "daily_skills",
        "channel": "social_dept",
        "description": "Центр дневного пребывания или помощь на дому по ИПР.",
        "how_to": "Обратитесь в отдел соцзащиты с выпиской из ИПР.",
        "typical_duration": "Уточняется в отделе соцзащиты",
        "required_documents": ["IPR_EXTRACT", "MSE_CERT", "ID_PARENT"],
        "default_deadline_days": 30,
        "responsible": "Центр оказания специальных социальных услуг",
        "executor": "family",
        "default_explanation": "Соцуслуги дают ребёнку занятия и присмотр, а семье — время на работу и отдых.",
    },
]

for _s in SERVICES:
    _s["agency"] = AGENCIES[_s["id"].split("_")[0]]
    _s.setdefault("optional_documents", [])
    _s.setdefault("extra_notes", [])
    _s.setdefault("produces", [])
    _s.setdefault("due_soon_days", None)
    _s.setdefault("available_cities", None)
    _s.setdefault("egov_url", None)

SERVICES_BY_ID = {s["id"]: s for s in SERVICES}

# --- Интервью: 12 вопросов-слотов (условия «когда задаётся» — в interview.py) ---
EDUCATION_OPTIONS = {
    "home": "Дома",
    "kg_regular": "Детский сад, обычная группа",
    "kg_inclusive": "Детский сад, инклюзивная группа с тьютором",
    "school_regular": "Школа, обычный класс без тьютора",
    "school_tutor": "Школа, есть тьютор",
    "school_special": "Школа, специальный класс",
    "home_schooling": "Обучение на дому",
}
IPAR_OPTIONS = {
    "SOC_BENEFIT": "Пособие",
    "SOC_SOCIAL_SERVICES": "Специальные социальные услуги",
    "SOC_SANATORIUM": "Санаторий",
    "SOC_TSR": "Технические средства (ТСР)",
}
NOTHING = "Пока ничего"
RED_FLAG_OPTIONS = [
    "Перестал делать то, что умел",
    "Агрессия или самоповреждение",
    "Сильно нарушились сон или еда",
]
NO_RED_FLAGS = "Ничего из этого"
BARRIER_OPTIONS = ["Работа", "Транспорт", "Язык", "Деньги", "Нет информации"]
NO_BARRIERS = "Ничего не мешает"

QUESTIONS: list[dict] = [
    {"id": "1", "slot": "rehab_status", "type": "choice", "llm": True,
     "text": "Что из рекомендаций ПМПК ребёнок уже получает: какие занятия, где и как часто?",
     "options": ["Получает все рекомендованные занятия", "Получает часть занятий", "Не получает"]},
    {"id": "1a", "slot": "rehab_blocker", "type": "multi", "llm": True,
     "text": "Почему пока не получается ходить на занятия?",
     "options": ["Очередь", "Нет мест", "Далеко ехать", "Не знали, куда обращаться"]},
    {"id": "2", "slot": "education_setting", "type": "choice", "llm": True,
     "text": "Где ребёнок проводит день: дома, в детском саду или в школе? Какая группа или класс?",
     "options": list(EDUCATION_OPTIONS.values())},
    {"id": "3", "slot": "med_followup", "type": "choice", "llm": True,
     "text": "Назначен ли следующий визит к врачу и удаётся ли выполнять назначения?",
     "options": ["Визит назначен, назначения выполняем", "Визит назначен, но выполнять назначения трудно", "Следующий визит не назначен"]},
    {"id": "4", "slot": "ipar_items", "type": "multi", "llm": True,
     "text": "Что из индивидуальной программы (ИПР) вы уже получили?",
     "options": list(IPAR_OPTIONS.values()) + [NOTHING]},
    {"id": "5", "slot": "mse_ref_status", "type": "choice", "llm": True,
     "text": "Говорил ли врач о направлении на медико-социальную экспертизу (МСЭ)?",
     "options": ["Да, направление выдали", "Говорил, но направления пока нет", "Нет, не говорил"]},
    {"id": "6", "slot": "red_flags", "type": "multi", "llm": False,
     "text": "Были ли за последний месяц такие изменения: перестал делать то, что умел; агрессия или самоповреждение; "
             "сильно нарушились сон или еда?",
     "options": RED_FLAG_OPTIONS + [NO_RED_FLAGS]},
    {"id": "7", "slot": "family_priority", "type": "text", "llm": True,
     "text": "Что сейчас для вашей семьи самое трудное?", "options": []},
    {"id": "8", "slot": "barriers", "type": "multi", "llm": False,
     "text": "Что мешает выполнять шаги: работа, транспорт, язык, деньги, нет информации?",
     "options": BARRIER_OPTIONS + [NO_BARRIERS]},
    {"id": "9", "slot": "family_owner", "type": "choice", "llm": True,
     "text": "Кто в семье будет заниматься шагами и есть ли у вас помощь?",
     "options": ["Мама", "Папа", "Оба родителя", "Бабушка или дедушка"]},
    {"id": "10", "slot": "family_goal", "type": "text", "llm": True,
     "text": "Что бы вы хотели, чтобы изменилось через 3 месяца?", "options": []},
    {"id": "11", "slot": "notify", "type": "choice", "llm": False,
     "text": "Как и когда вам удобно получать напоминания?",
     "options": ["WhatsApp, утром", "WhatsApp, вечером", "SMS, утром", "SMS, вечером", "Звонок куратора"]},
    {"id": "12", "slot": "summary_confirmed", "type": "confirm", "llm": False,
     "text": "Правильно ли я понял?", "options": ["Да, всё верно"]},
]
QUESTIONS_BY_ID = {q["id"]: q for q in QUESTIONS}
SLOT_LABELS = {
    "rehab_status": "Занятия по рекомендациям ПМПК",
    "rehab_blocker": "Почему не получается",
    "education_setting": "Где ребёнок днём",
    "med_followup": "Наблюдение у врача",
    "ipar_items": "Что получено по ИПР",
    "mse_ref_status": "Направление на МСЭ",
    "red_flags": "Изменения за месяц",
    "family_priority": "Самое трудное сейчас",
    "barriers": "Что мешает",
    "family_owner": "Кто занимается шагами",
    "family_goal": "Цель на 3 месяца",
    "notify": "Напоминания",
}

# --- Три синтетических кейса (даты от demo_today = 2026-09-30) ---
SCENARIOS: dict[str, dict] = {
    "1": {
        "child_alias": "Семья 1",
        "summary": "Ранний этап: 18 месяцев, заключения нет, к педиатру ещё не обращались.",
        "birth_date": "2025-03-30",
        "city": "Кызылорда",
        "language": "kk",
        "intake": {
            "has_conclusion": False, "conclusion_date": None, "dispensary": False,
            "pmpk_status": "none", "pmpk_date": None,
            "mse_status": "none", "mse_valid_until": None,
            "mchat_status": "none", "mchat_date": None,
            "pediatrician_visited": False,
            "documents": [],
        },
        "answers": {
            "2": EDUCATION_OPTIONS["home"],
            "6": [NO_RED_FLAGS],
            "7": "Не понимаем, куда идти сначала: ребёнок почти не говорит, и мы волнуемся.",
            "8": ["Нет информации"],
            "9": "Мама",
            "10": "Чтобы у нас был понятный план и мы начали занятия.",
            "11": "WhatsApp, вечером",
        },
    },
    "2": {
        "child_alias": "Семья 2",
        "summary": "Административный затор: 8 лет, ПМПК не пройдена, справка МСЭ истекла, в школе без тьютора.",
        "birth_date": "2018-09-30",
        "city": "Петропавловск",
        "language": "ru",
        "intake": {
            "has_conclusion": True, "conclusion_date": "2021-09-30", "dispensary": True,
            "pmpk_status": "none", "pmpk_date": None,
            "mse_status": "expired", "mse_valid_until": "2026-01-30",
            "mchat_status": "none", "mchat_date": None,
            "pediatrician_visited": True,
            "documents": ["MED_CONCLUSION", "MSE_CERT"],
        },
        "answers": {
            "2": EDUCATION_OPTIONS["school_regular"],
            "3": "Визит назначен, назначения выполняем",
            "4": [NOTHING],
            "5": "Нет, не говорил",
            "6": [NO_RED_FLAGS],
            "7": "Справка закончилась, выплаты остановились, а в школе без помощника трудно.",
            "8": ["Работа", "Нет информации"],
            "9": "Мама",
            "10": "Продлить справку и чтобы в школе появился тьютор.",
            "11": "SMS, вечером",
        },
    },
    "3": {
        "child_alias": "Семья 3",
        "summary": "Продление справки: 6 лет, всё оформлено, справка МСЭ действует до 10.11.2026.",
        "birth_date": "2020-09-30",
        "city": "Шымкент",
        "language": "ru",
        "intake": {
            "has_conclusion": True, "conclusion_date": "2023-09-30", "dispensary": True,
            "pmpk_status": "valid", "pmpk_date": "2025-09-15",
            "mse_status": "valid", "mse_valid_until": "2026-11-10",
            "mchat_status": "none", "mchat_date": None,
            "pediatrician_visited": True,
            "documents": ["MED_CONCLUSION", "MSE_CERT", "IPR_EXTRACT", "PMPK_CONCLUSION"],
        },
        "answers": {
            "1": "Получает все рекомендованные занятия",
            "2": EDUCATION_OPTIONS["kg_inclusive"],
            "3": "Визит назначен, назначения выполняем",
            "4": list(IPAR_OPTIONS.values()),
            "6": [NO_RED_FLAGS],
            "7": "Боимся пропустить продление справки: в прошлый раз документы собирали долго.",
            "8": [NO_BARRIERS],
            "9": "Оба родителя",
            "10": "Спокойно продлить справку и подготовиться к школе.",
            "11": "WhatsApp, утром",
        },
    },
}
